### ISSUE TITLE
Can't escape ^ character

### ISSUE THREAD

**Issue by conradoplg** [mmarkdown/mmark#104]
I've tried using `\^` but it doesn't work; the backslash is added to the output.

**Comment by miekg** [comment]
~~~
% ./mmark -fragment -html <(echo 'We have a ^ character here')
<p>We have a ^ character here</p>
~~~

**Comment by conradoplg** [comment]
Sorry for not adding an example...

```
% ./mmark -fragment -html <(echo 'x^2*y^2')
<p>x<sup>2*y</sup>2</p>

% ./mmark -fragment -html <(echo 'x\^2*y\^2')
<p>x\<sup>2*y</sup>2</p>
```

I don't want the output to use `<sup>`, because `xml2rfc` render the exponent between parenthesis in text mode.

**Comment by miekg** [comment]
Ah. Yes that would make sense.

**Comment by miekg** [comment]
Ok. This turned out to be 1 char bugfix. I'll push that later today/this
evening.
