### ISSUE TITLE
Allow seriesInfo value override on command line

### ISSUE THREAD

**Issue by rolandshoemaker** [mmarkdown/mmark#109]
(This is extremely ID/RFC specific.)

When writing IDs it would be extremely useful to be able to define the draft revision via a command line flag rather than setting it in the markdown file itself. i.e I'd like to be able to set in my front matter
```
[seriesInfo]
value = draft-shoemaker-wg-things"
```

and then come build time run `mmark --seriesInfo draft-shoemaker-wg-things-04 draft-shoemaker-wg-things.md`, or even `mmark --seriesInfoNumber 04 draft-shoemaker-wg-things.md` to set/append the draft revision to the series value.

This would better match some of the ID workflows I've participated in in the past, but is also entirely workflow dependent so if you're opposed I totally get it!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[mmarkdown/mmark] Allow seriesInfo ..." ]
>(This is extremely ID/RFC specific.)
>
>When writing IDs it would be extremely useful to be able to define the draft revision via a command line flag rather than setting it in the markdown file itself. i.e I'd like to be able to set in my front matter
>```
>[seriesInfo]
>value = draft-shoemaker-wg-things"
>```
>
>and then come build time run `mmark --seriesInfo draft-shoemaker-wg-things-04 draft-shoemaker-wg-things.md`, or even `mmark --seriesInfoNumber 04 draft-shoemaker-wg-things.md` to set/append the draft revision to the series value.
>
>This would better match some of the ID workflows I've participated in in the past, but is also entirely workflow dependent so if you're opposed I totally get it!

I don't really want to go into this direction as I'm trying to make the document
completely self contained, i.e. same document -> same output.

Why is updating the number in the document itself hard?

Potentially I can write you a small filter (https://github.com/mmarkdown/filter/) which
you can just include in the pipeline, alternatively this can be done with editing the xml
in flight?

**Comment by rolandshoemaker** [comment]
Totally reasonable. The main pain point I'm trying to address is from working on IDs using github. People often end up linking to the raw markdown and assuming, because it has a specific version tag in the document, that the version reflects the current content which is often incorrect (i.e. after. submitting a version -01 any changes to the document on github are likely to actually be representative of an unpublished -02).

That said after thinking about this a bit more I think this is better addressed by defining a better git workflow than in mmark itself. I'll close this ticket since I agree it's better to keep the document self contained.

Also just wanted to say thanks for your work on this project! Coming from using other ID/RFC tooling this has been a really pleasant experience.

**Comment by miekg** [comment]
On Tue, 24 Mar 2020, 16:56 Roland Bracewell Shoemaker, <
notifications@github.com> wrote

> Also just wanted to say thanks for your work on this project! Coming from
> using other ID/RFC tooling this has been a really pleasant experience.
>

Thanks!

>
