### ISSUE TITLE
CRLF line endings in Markdown files creates bogus output

### ISSUE THREAD

**Issue by robUx4** [mmarkdown/mmark#117]
When this file is stored with Linefeed (LF) line ending, it produces a (mostly) correct output:

```markdown
{mainmatter}

Test

{backmatter}
```

When stored with CRLF (the Windows way) it produces bogus output:
```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- name="GENERATOR" content="github.com/mmarkdown/mmark Mmark Markdown Processor - mmark.miek.nl" -->

</front>

<middle>
<t>

Test

</t>kmatter}

</middle>
```

The `</front>` with no beginning exists in both version.

**Comment by miekg** [comment]
see https://github.com/gomarkdown/markdown/issues/154 
and https://github.com/gomarkdown/markdown/issues/137
