### ISSUE TITLE
Invalid XML when generating an FYI document

### ISSUE THREAD

**Issue by kategray** [mmarkdown/mmark#134]
# To help us debug your issue please add these details.

## What went wrong?

xml2rfc failed with the error `draft-credentsys-kdf-00.xml(3): Error: Invalid attribute category for element rfc, at /rfc`

## What version of mmark are you using?

2.2.10

## What command line did you use?

`draft-credentsys-kdf-00.xml(3): Error: Invalid attribute category for element rfc, at /rfc`

## What platform (Linux/Apple/Windows)?

- [ ] Linux
- [X] Apple
- [ ] Windows

I created a document with the following seriesInfo:

```ini
[seriesInfo]
name = "RFC"
value = "1"
stream = "independent"
status = "fyi"
```

This results in the following xml:

```xml
<rfc version="3" ipr="trust200902" docName="1" submissionType="independent" category="fyi" xml:lang="en" xmlns:xi="http://www.w3.org/2001/XInclude" number="1">
```

Per RFC7991 2.45.1, category is deprecated.

```
2.45.1.  "category" Attribute
   Deprecated; instead, use the "name" attribute in <seriesInfo>.
```

Unfortunately, xml2rfc refuses to accept a category of fyi as valid and exits.  A status of FYI in a seriesinfo element is valid, however.

**Comment by miekg** [comment]
so it's very unclear _what_ is currently the way of doing this, 7991 isn't really what's implemented in xml2rfc (and the update to 7991 isn't finished yet). `category` is supported (or allowed?), but the value here isn't.

Tweaked the documented and code a bit to now allow it. Got something going with (in rfc/2100.md):
~~~
[seriesInfo]
name = "FYI"
value = "2100"
stream = "IETF"
status = "informational"
~~~
