### ISSUE TITLE
nested superscript

### ISSUE THREAD

**Issue by dericed** [mmarkdown/mmark#136]
Hi, I'm working on proofreading RFC9043 and adding a note as a feature request.

The source document was created via mmark and was then edited in AUTH48. At https://www.rfc-editor.org/authors/rfc9043.html#figure-15 there's a nested subscript. The AUTH48 editor finalized this expression as `S<sub>i+1,C<sub>i</sub></sub>` or S<sub>i+1,C<sub>i</sub></sub>.

With mmark syntax I think the closest we can get is `S~i+1,C_(i)~` which renders as `S<sub>i+1,C_(i)</sub>` or S<sub>i+1,C_(i)</sub>.

**Comment by miekg** [comment]
Hi Dave... I can see this would be neat. It's tricky though, mainly because the start and closing character are identical; I'm worried the parser won't stop searching for the closing `~`, or IOW how does it know it's nested and not just 2 subscripts?

**Comment by miekg** [comment]
I think I'm closing this with wont-fix. Doing this properly means we need to support math syntax in both markdown and in the resulting RFC. (Ab)using super- and sub-scripts can only get you so far.

**Comment by dericed** [comment]
Np, as I work for the AUTH48 process I may add in a few more issues. I know some of these are quite niche, so no issue about wont-fix.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [mmarkdown/mmark] nested supers..." ]
>Np, as I work for the AUTH48 process I may add in a few more issues. I know
>some of these are quite niche, so no issue about wont-fix.

Might also be worth exploring math XML with the XML steering group, at least there is
syntax available in markdown to allow for this.
