### ISSUE TITLE
xml:refcontent is stripped from the resulting xml file

### ISSUE THREAD

**Issue by tmarkovski** [mmarkdown/mmark#142]
When using XML in the markdown, when `<reference>` attribute contains `<refcontent>` it is stripped in the resulting XML file.

For example, in my markdown file I added the following:

```
<reference anchor="ECMA-262" target="https://www.ecma-international.org/ecma-262/10.0/index.html">
  <front>
    <title>ECMAScript 2019 Language Specification</title>
    <author>
      <organization>ECMA International</organization>
    </author>
    <date year="2019" month="June"/>
  </front>
  <refcontent>Standard ECMA-262 10th Edition</refcontent>
</reference>
```

but in the generated XML, I get this content

```
<reference anchor="ECMA-262" target="https://www.ecma-international.org/ecma-262/10.0/index.html">
  <front>
    <title>ECMAScript 2019 Language Specification</title>
    <author>
      <organization>ECMA International</organization>
    </author>
    <date year="2019" month="June"></date>
  </front>
</reference>
```

Any reason why this would be the case?

**Comment by miekg** [comment]
That's because these are parsed and then outputted again. Refcontent is missing in the internal definition. 
Because the current xml3 lacks an RFC document, it's hard to keep track of updates

**Comment by tmarkovski** [comment]
Thanks for the quick response. I think I saw a reference to it at https://github.com/mmarkdown/mmark/blob/c5c8318c852efa4955e97ef049a2cd45672b74ac/mast/reference/reference.go#L82 , but I'm not sure if this is used. I assumed since its the struct, it should be understood.

I'll make sure to update my XML manually to get around this.

**Comment by miekg** [comment]
you are using mmark from the master branch?

**Comment by tmarkovski** [comment]
No, using a docker from https://github.com/oauthstuff/markdown2rfc, which I realize now points to a rather old release.
I guess I should try use the latest form this repo.

**Comment by miekg** [comment]
Please do. Think I even triggered a release with this fix in it (omitempty
might be a thing I need to add still)

**Comment by tmarkovski** [comment]
Latest master (2.2.16) worked, while latest from releases (2.2.10) didn't.
I should've used the master version from the start. Thank you for the fast response!

**Comment by miekg** [comment]
I see that I didn't do any releases (due to using wrong github token). I've pushed 2.2.16 just now.
