### ISSUE TITLE
Is the lack of the NoIntraEmphasis parser Extension intentional?

### ISSUE THREAD

**Issue by dwaite** [mmarkdown/mmark#143]
When writing specifications, it is not uncommon to deal with parameters which are camel_cased_strings. By default, mmark will render these as camel<I>cased</I>strings because of the lack of the `NoIntraEmphasis` extension.

I didn't see any option or comment regarding why this extension is the one extension missing from gomarkdown's `CommonExtensions` definition within mmark's parser.

 Would it be possible to add this extension, even if as an option which needs to be enabled within the title block?

**Comment by miekg** [comment]
Not intentionally, so we might as well add it. The only problem now becomes if this would be a backwards incompatible change?

**Comment by miekg** [comment]
solved with #147, if that doesn't show up any problems, we should remove the flag, default to added the extensions and call it a day.

**Comment by dwaite** [comment]
@miekg Just to make sure it is clear: this still defaults to the same behavior -  its an opt-out by -intra-emphasis=false

**Comment by miekg** [comment]
Ah..we might want to flip that (soon) and wait for any fall out
