### ISSUE TITLE
Offer to document more existing Markdown RFC sources

### ISSUE THREAD

**Issue by danshearer** [mmarkdown/mmark#165]
# To help us debug your issue please add these details.

I volunteer to write documentation pointing to more examples of mmark Markdown-formatted RFCs. People are using mmark to write their RFCs so presumably the sources must be available somewhere. At least for RFC 7328, which is about Markdown use :-), and RFCs 7719 and 6781, both written by the author of mmark.  I have looked but just not been able to find such sources.

And thanks for mmark. It's great.

## What went wrong?

I came to write the "IANA Considerations" section for my internet draft and realised that having more examples would save me a lot of time. I *think* there a YAML block for this section, for example.

## What version of mmark are you using?

2.23

**Comment by miekg** [comment]
Hi, thanks for liking mmark. 

You want to include some more examples in the rfc/ subdir of this project? That's fine by me!

The mentioned RFCs predate some of this stuff, so don't think there were fully markdownyfied at the time, but converting them is relative easy - the plaintext is almost the conversion. Happy to include those.

mmark does not use yaml, but toml and that's only used in the title block. Anything else in the main text will be XML for including references (as those are published in XML format)

**Comment by danshearer** [comment]
I see! I noticed the IANA section seems quite formulaic so I thought it might be toml too. Oh well. It might be worth mentioning that the only templating is in the top section.

So that suggests that when I followed your invitation in the docs and did this:
```
  diff -u  orig/rfc5841.txt 5841.txt
```
that mostly the differences are careful manual changes, rather than improvements as a result of using templating. Bother! I was hoping for a little more magic, and URLs to Markdownified RFCs all over the place.

> the plaintext is almost the conversion. Happy to include those.

That would be very helpful, if you can spare the time.

We are writing a data format specification, so it will have sections in common with many other RFCs. Naturally I was hoping that one of these was already markdownified. We will certainly make the markdown available.

Perhaps in the mmark docs you could encourage users to make their markdown available. It's not like they are intended to be a big secret.

Best and thanks again

Dan

**Comment by miekg** [comment]
I can't make the time to add more RFCs to this repo, also most RFCs don't contain new and special constructs, so the are relatively boring markdown documents.

Having the markdown in some IETF repo might make sense, would be cool if the IETF also stored the markdown file in the data-tracker for instance.

Happy to include documentation changes if you send a PR this way.

**Comment by miekg** [comment]
unsure if this issue results in any work items, closing
