### ISSUE TITLE
Minimum version of xml2rfc has recently changed

### ISSUE THREAD

**Issue by danshearer** [mmarkdown/mmark#172]
# To help us debug your issue please add these details.

## What went wrong?

The minimum required version for xml2rfc seems to have changed. Until a few weeks ago it was around 2.47.

What is the new minimum version?

I notice that v3 output is specified, including by default, so I suspect xml2rfc might need to be v3 as well. That isn't a problem, but it would be helpful to know what is intended.

```
mmark/rfc/1035.xml(2373): Error: Did not expect an <iref> here, skipping it 
  :
1035.xml(0): Error: Type IDREF doesn't allow value 'rfc.index.*', at /rfc/back/section[1]/t/xref[1]
  :
1035.xml(0): Error: Element li has extra content: t, at /rfc/back/section[1]/ul/li[1]/t   
 ```

## What version of mmark are you using?

Git master as of today, 2022-01-29

mmark -version reports 2.2.25

## What is the *most* minimal markdown snippets that shows the problem?

```
cd rfc
make txt  
```

**Comment by miekg** [comment]
support for v2 xml is been dropped a while ago.

Currently the spec _is_ what xml2rfc implements, as rfc 7991 needs a -bis document. 

So I recommend just upgrading to the latest xml2rfc

**Comment by danshearer** [comment]
> So I recommend just upgrading to the latest xml2rfc

Ok that is helpful, however, it would be useful if there was a way for mmark to say this. The old version 2.47 of xml2rfc will still produce output for the files you supply with mmark in the rfc/ directory, albeit with some warnings. So my first problem is that the toolchain *looks* like it works. But as you point out, it probably does not, or at least there is fragility.

Perhaps it is not appropriate for mmark to do detection for a tool later in the toolchain, but maybe you can put some advice in the docs.

But then, what is the definition of "the latest xml2rfc" ? Is it:

# https://svn.ietf.org/svn/tools/xml2rfc/trunk/ , currently "xml2rfc - Revision 4090: /trunk", or
# https://svn.ietf.org/svn/tools/xml2rfc/releases/ , which is a tarball with no clues in its name, or
# something else?

thanks!

**Comment by danshearer** [comment]
> The old version 2.47 of xml2rfc will still produce output for the files you supply with mmark in the rfc/ directory, albeit with some warnings. 

No it doesn't. My OS was confused and reported an old version.

I can confirm that xmlrfc 3.12.0 produces output for the samples in mmark/rfc.

But I do not know if 3.12.0 is "good".

**Comment by miekg** [comment]
Latest version if whatever shows up at pypi: https://pypi.org/project/xml2rfc/

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [mmarkdown/mmark] Minimum versi..." ]
>    The old version 2.47 of xml2rfc will still produce output for the files you
>    supply with mmark in the rfc/ directory, albeit with some warnings.
>
>No it doesn't. My OS was confused and reported an old version.
>
>I can confirm that xmlrfc 3.12.0 produces output for the samples in mmark/rfc.
>
>But I do not know if 3.12.0 is "good".

It's "good" because it's the latest... :/ I think you want/need guidance from the RFC
editor/ietf on what is supported... So these questions might be more appropriate to ask in
those venues.

As said, there is no (RFC) document that describes the current schema, e.g. the <contact>
element is not described except in the DTD included in xml2rfc's tarball.

There is also no 'stable/long term support' release from xml2rfc, so mmark is following a
moving target and can only (try to) support the latest version.

**Comment by miekg** [comment]
added a few words here: https://mmark.miek.nl/post/faq/#what-version-of-xml2rfc-is-supported
