### ISSUE TITLE
Is it possible to disable char-num replacement?

### ISSUE THREAD

**Issue by ktmf01** [mmarkdown/mmark#174]
According to RFC 7997, escaping UTF-8 characters is not always necessary. Section 3.1

```
  Where the use of non-ASCII characters is purely part of an example
  and not otherwise required for correct protocol operation, escaping
  the non-ASCII character is not required.
```
Is it possible to disable the `<u format="char-num">` replacement in certain sections of a document?

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "[mmarkdown/mmark] Is it possible to..." ]
>According to RFC 7997, escaping UTF-8 characters is not always necessary.
>Section 3.1
>
>  Where the use of non-ASCII characters is purely part of an example
>  and not otherwise required for correct protocol operation, escaping
>  the non-ASCII character is not required.
>
>Is it possible to disable the <u format="char-num"> replacement in certain
>sections of a document?

nope, this is xml2rfc doing it: https://xml2rfc.tools.ietf.org/xml2rfc-doc.html#name-u-new-2
I don't know when or if utf-8/unicode will be the default.

Would be nice to just have `format=char`, but that's also not supported. Don't know why

**Comment by ktmf01** [comment]
Thanks
