### ISSUE TITLE
Request: Make note of newline character sensitivity?

### ISSUE THREAD

**Issue by paragonie-security** [mmarkdown/mmark#176]
# To help us debug your issue please add these details.

While trying to update the PASETO RFC draft, I kept getting this error:

```
$ make
mmark paseto.md > draft-paragon-paseto-rfc-02.xml
xml2rfc --v2 --html draft-paragon-paseto-rfc-02.xml
Error: Unable to parse the XML document: draft-paragon-paseto-rfc-02.xml
 /home/robyn/projects/paseto-rfc/draft-paragon-paseto-rfc-02.xml: Line 45: Extra content at the end of the document
```

After a lot of wrong guesses, I found out the issue: I'm using a VirtualBox shared folder. My host OS is Windows, which checked out newlines as CRLF rather than just LF. This caused the title block to not be parsed, which caused invalid XML to be generated. This caused a downstream failure with xml2rfc.

## What version of mmark are you using?

Version 2,2,25.

## What is the *most* minimal markdown snippets that shows the problem?

Take a valid `.md` file from your test files, run `unix2dos` on that file, then pass it to the `mmark` program.

## Recommendation

One of the following:

* Support CRLF instead of just LF, or
* Clearly document this behavior so other people will know to normalize their line endings

**Comment by miekg** [comment]
Odd, https://github.com/mmarkdown/mmark/blob/master/mmark.go#L76 should
normalize those newlines

**Comment by paragonie-security** [comment]
Interesting. I'm not sure what caused this specific failure, but we know on our end how to fix it.

Virtualbox shared folders and inconsistent behavior with Git + Jetbrains IDEs over the years might've created a weird state, which was fixed when I ran `dos2unix`.
