### ISSUE TITLE
mmark releases

### ISSUE THREAD

**Issue by kesara** [mmarkdown/mmark#178]
# To help us debug your issue please add these details.

[Author Tools](https://author-tools.ietf.org) relies on mmark GitHub releases.
Consider cutting new releases to get the new changes to author tools.

## What went wrong?

Nothing.

## What version of mmark are you using?

2.2.25

## What is the *most* minimal markdown snippets that shows the problem?

N/A

**Comment by miekg** [comment]
2.2.25 is the latest release? You need a version bump for something?

**Comment by kesara** [comment]
Version bump with latest changes would be great.

Because there's been few source updates since 2.2.25 release.

Frequent version bumps will make sure new changes will get into services like author tools quickly.

**Comment by miekg** [comment]
bumped the version.

**Comment by kesara** [comment]
Thank you!
