### ISSUE TITLE
mmark output not accepted by xml2rfc

### ISSUE THREAD

**Issue by ktmf01** [mmarkdown/mmark#181]
The following input renders fine

```
%%%
title = "Test"

[seriesInfo]
name = "Internet-Draft"
stream = "IETF"
status = "standard"
value = "0"

[[author]]
fullname="Martijn van Beurden"

%%%

.# Abstract

Test

{mainmatter}

# bit Rice parameter

More test
```

But if I change the section title to `# 5 bit Rice parameter`  I get

```
test.xml(20): Error: Invalid attribute anchor for element section, at /rfc/middle/section
/home/pi/bin/flac-specification/test.xml(3): Error: Invalid document before running preptool.
Unable to complete processing test.xml
```

Don't know whether this is deliberate or not, it seems xml2rfc doesn't like anchors starting with a digit?

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "[mmarkdown/mmark] mmark output not ..." ]
>test.xml(20): Error: Invalid attribute anchor for element section, at /rfc/middle/section
>/home/pi/bin/flac-specification/test.xml(3): Error: Invalid document before running preptool.
>Unable to complete processing test.xml
>
>Don't know whether this is deliberate or not, it seems xml2rfc doesn't like
>anchors starting with a digit?

Haven't checked, but could very well be the case. You probable want a header-id to set the
reference for the header

```
# 5 Bit Stuff {#my5bitid}
```

**Comment by ktmf01** [comment]
Thanks!
