### ISSUE TITLE
Incorrect GitHub Organization URL 

### ISSUE THREAD

**Issue by rrrix** [mmarkdown/mmark#194]
Hi @miekg,

The Organization URL of `github.com/mmarkdown` appears to be incorrect.

It currently is `https://mmark.nl/` which appears to be some kind of SEO affiliate link aggregator unrelated to the mmarkdown/mmark project.

I believe it should be `https://mmark.miek.nl/` (the same URL listed on the `github.com/mmarkdown/mmark` project page).

```shell
$ gh api \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  /orgs/mmarkdown | jq "{id, login, name, description, blog, html_url, url}"
```
```json5
{
  "id": 33029025,
  "login": "mmarkdown",
  "name": "Mmarkdown",
  "description": "Mmark markdown parser",
  "blog": "https://mmark.nl",
        // ^^^^^^^^^^^^^^^^ -- should this be "https://mmark.miek.nl/"?
  "html_url": "https://github.com/mmarkdown",
  "url": "https://api.github.com/orgs/mmarkdown"
}
```

You should be able to update it here: https://github.com/organizations/mmarkdown/settings/profile

Apologies in advance if this is the wrong place to put this, or if the Organization URL is configured correctly.

**Comment by miekg** [comment]
Ha thanks, totally forgot about the url there.

Updated to point to mmark.miek.nl

Thanks!
