### ISSUE TITLE
Error referencing internet draft by version

### ISSUE THREAD

**Issue by dwaite** [mmarkdown/mmark#195]
# To help us debug your issue please add these details.
When attempting to reference an internet draft by version , e.g. using `[@!I-D.irtf-cfrg-bbs-signatures#03]`, it attempts to resolve `https://bib.ietf.org/public/rfc/bibxml-ids/reference.I-D.irtf-cfrg-bbs-signatures-03.xml`, which gives a 404. `https://bib.ietf.org/public/rfc/bibxml-ids/reference.I-D.irtf-cfrg-bbs-signatures.xml` does load.

From the API documentation, I was unable to figure out where this URL form comes from. Closest I was able to find was:
`https://bib.ietf.org/api/v1/ref/ids/draft-irtf-cfrg-bbs-signatures-03/`

**Comment by miekg** [comment]
I thought this was the final resting place for ID references, let me look again.

this value is hardcoded in the source of mmark

**Comment by miekg** [comment]
hmmm, I can make that change, but how does one reference an older I-D then?

**Comment by dwaite** [comment]
Picking a known ancient-ish I-D (from 2008), 

https://bib.ietf.org/api/v1/ref/ids/draft-smith-opentoken-02/ resolves. (based on https://bib.ietf.org/api/v1/#operation/getCitationByReferenceId)

https://bib.ietf.org/public/rfc/bibxml-ids/reference.I-D.smith-opentoken-02.xml does not.

However, I don't have any knowledge of how bib.ietf.org is run.

**Comment by miekg** [comment]
eh, brrr. I think I'll need to ask around what the current status is...

**Comment by miekg** [comment]
https://authors.ietf.org/en/references-in-rfcxml

> The anchors for Internet-Drafts are "I-D.<name without "draft-" or the version number>".

ok, that's an easy change to make, but I'm wondering if/how you then ref a specific version.

**Comment by miekg** [comment]
I've sent an email to hopefully the folks who know more about this and asked for help/guidance
