### ISSUE TITLE
Error referencing RFC drafts

### ISSUE THREAD

**Issue by RafaelAPB** [mmarkdown/mmark#196]
I have a problem with generating RFC and ID citations in the format [@RFC_ID], as you can see in line 159 of https://github.com/ietf-satp/draft-ietf-satp-core/edit/main/draft-ietf-satp-core.md. Any ideas why? 

I'm using mmark v2.2.10 as in https://github.com/martinthomson/i-d-template/blob/main/docker/action/Dockerfile

Thank you

Related to #195

**Comment by miekg** [comment]
I'll pick up your markdown,

**Comment by miekg** [comment]
dupping this into #195
