### ISSUE TITLE
Support more `rfc` attributes

### ISSUE THREAD

**Issue by str4d** [mmarkdown/mmark#198]
## What went wrong?

One of the editorial changes that the RFC Editor made to an ID's XML generated from `mmark` was to add the following attributes to `<rfc>`:
```
symRefs="true"
sortRefs="true"
tocInclude="true"
```

[`symRefs`](https://datatracker.ietf.org/doc/html/rfc7991#section-2.45.13) and [`tocInclude`](https://datatracker.ietf.org/doc/html/rfc7991#section-2.45.15) both default to `true`, so it doesn't matter whether they are set or absent in this case. But [`sortRefs` defaults to `false`](https://datatracker.ietf.org/doc/html/rfc7991#section-2.45.11), so it isn't possible to replicate the RFC Editor's XML changes in the Markdown source.

It would be useful for `mmark` to support configuring the full non-deprecated set of `rfc` attributes, but at a minimum `sortRefs` would be useful given that the RFC Editor does (with a sample size of 1) use it.

## What version of mmark are you using?

2.2.36

**Comment by miekg** [comment]
`sortRefs` looks reasonable, can you make a (smaller) PR with just that change?

**Comment by str4d** [comment]
I've extracted the `sortRefs` commit from #199 as its own PR: #201.

**Comment by miekg** [comment]
if an authoritative source tells me this other attrs are important, I'll happily include them, until then: closing

**Comment by qasimwarraich** [comment]
First of all, I am sorry to bump a closed issue (even though it's only a week old)

I am definitely not an authoritative source 😓, but if you would consider including a title configuration option for `symRefs` I would happily make a PR :).

**Comment by miekg** [comment]
Thanks, but it's not so much about what we can do, but what the rfc-editors
wants.

These PIs (process instructions) are def. something they want to get rid off
