### ISSUE TITLE
`consensus` attribute applies to more than the IETF stream

### ISSUE THREAD

**Issue by str4d** [mmarkdown/mmark#200]
Currently, the `consensus` attribute is rendered in the `<rfc>` block if and only if the document is in the IETF stream:
https://github.com/mmarkdown/mmark/blob/3d25d9375c96315e75624f8f5b9d814d870e35fe/render/xml/title.go#L46-L52

However, the IRTF stream also uses this attribute to switch between two kinds of boilerplate (https://www.rfc-editor.org/styleguide/headers-and-boilerplate/). It looks like IAB also has consensus-related boilerplate, but I don't have confirmation from anyone there that the `consensus` attribute is used for this (whereas I do for IRTF).

**Comment by str4d** [comment]
#199 updates the renderer to output the `consensus` attribute for IRTF stream in addition to IETF. Someone should confirm whether or not it should be output for IAB stream documents before closing this issue.

**Comment by miekg** [comment]
there is noone here (AFAIK) from the IETF. I certainly can't say if the above is true.
(this is way a update of RFC 7991 would be welcome)

**Comment by miekg** [comment]
`IRTF` is the `SubmissionType we can check for here?
