### ISSUE TITLE
Prebuilt binaries are missing

### ISSUE THREAD

**Issue by suzuki-shunsuke** [mmarkdown/mmark#207]
From mmark v2.23.7, prebuilt binaries aren't released at GitHub Releases.

https://github.com/mmarkdown/mmark/releases/tag/v2.2.39

<img width="495" alt="image" src="https://github.com/mmarkdown/mmark/assets/13323303/f0f20ec2-4179-4f41-9445-7000a5c75544">

Could you release prebuilt binaries?
I think it's useful to release prebuilt binaries automatically with [GoReleaser](https://goreleaser.com/) or something by CI.

**Comment by miekg** [comment]
See https://github.com/mmarkdown/mmark/issues/190
I don't have the time to explore this... If there is a simple way to make
x86, arm and a windows exe please go ahead

**Comment by suzuki-shunsuke** [comment]
Thank you for your reply.
I'm woking on setting up a release workflow with GoReleaser.

- https://github.com/mmarkdown/mmark/pull/208
