### ISSUE TITLE
Provide release notes

### ISSUE THREAD

**Issue by bsiegert** [mmarkdown/mmark#217]
Hi! pkgsrc maintainer for mmark here (https://pkgsrc.se/textproc/go-mmark).

It would be nice if releases could have a changelog and/or release notes attached to them. We usually attach these when we do package updates. You can probably configure goreleaser to do that for you.

**Comment by miekg** [comment]
There is only git log -p, I don't have time to implement this, nor do I have time to type something that's can be converted into a readable changelog

**Comment by miekg** [comment]
Please do

thank you
