### ISSUE TITLE
Is it possible to specify metadata using YAML?

### ISSUE THREAD

**Issue by wiktor-k** [mmarkdown/mmark#219]
## What went wrong?

Well, nothing in particular. I was wondering if it would be possible to specify document metadata using YAML instead of TOML. It seems YAML metadata is fairly standard in Markdown processing tools, eg. GitHub Docs uses them: https://docs.github.com/en/contributing/writing-for-github-docs/using-yaml-frontmatter

## What version of mmark are you using?

2.2.25+dfsg1-2 from debian.

## What is the *most* minimal markdown snippets that shows the problem?

```
---
title: "OpenPGP fingerprints in the DNS"
abbrev: "PGP fingerprints in the DNS"
ipr: "trust200902"
submissiontype: "independent"
date: 2024-02-16T10:27:00Z

seriesInfo:
  name: "Internet-Draft"
  value: "draft-00"
  stream: "independent"
  status: "informational"

authors:
  - initials: "W."
    surname: "Kwapisiewicz"
    address:
     email: "..."
---

.# Abstract

This document specifies a new scheme for verifying authenticity of OpenPGP
certificates through the DNS system. The certificates to be verified can be
organization OpenPGP CA (Certificate Authority) certificates or individual
certificates of owners of the DNS zone.
```

Thanks for your time! :wave:

**Comment by miekg** [comment]
At the moment only TOML is support, but I can see the appeal. I wont have time to work on
this, but happy to look at PR. Meanwhile a online yaml to toml converter could be used?




[ Quoting ***@***.***> in "[mmarkdown/mmark] Is it possible to..." ]
>What went wrong?
>
>Well, nothing in particular. I was wondering if it would be possible to specify
>document metadata using YAML instead of TOML. It seems YAML metadata is fairly
>standard in Markdown processing tools, eg. GitHub Docs uses them: https://
>docs.github.com/en/contributing/writing-for-github-docs/using-yaml-frontmatter
>
>What version of mmark are you using?
>
>2.2.25+dfsg1-2 from debian.
>
>What is the most minimal markdown snippets that shows the problem?
>
>---
>title: "OpenPGP fingerprints in the DNS"
>abbrev: "PGP fingerprints in the DNS"
>ipr: "trust200902"
>submissiontype: "independent"
>date: 2024-02-16T10:27:00Z
>
>seriesInfo:
>  name: "Internet-Draft"
>  value: "draft-00"
>  stream: "independent"
>  status: "informational"
>
>authors:
>  - initials: "W."
>    surname: "Kwapisiewicz"
>    address:
>     email: "..."
>---
>
>.# Abstract
>
>This document specifies a new scheme for verifying authenticity of OpenPGP
>certificates through the DNS system. The certificates to be verified can be
>organization OpenPGP CA (Certificate Authority) certificates or individual
>certificates of owners of the DNS zone.
>
>Thanks for your time! 👋
>
>—
>Reply to this email directly, view it on GitHub, or unsubscribe.
>You are receiving this because you are subscribed to this thread.*Message ID:
>***@***.***>
>
/Miek

--
Miek Gieben

**Comment by wiktor-k** [comment]
> At the moment only TOML is support, but I can see the appeal. I wont have time to work on this, but happy to look at PR.

Great, I was looking for a confirmation that this doesn't look okay only in *my* head.

I'll add that to my ever growing list of TODOs :)
