### ISSUE TITLE
Support duplicate footnotes

### ISSUE THREAD

**Issue by 747** [mmarkdown/mmark#25]
# To help us debug your issue please add these details.
Is it possible to support multiple references to a footnote content? Seems that blackfriday has implemented the feature through russross/blackfriday#366.

```
Sentence one[^1]. Sentence two[^1]. Sentence three[^1].

[^1]: They should all refer to here.
```

As of Hugo 0.49, whose blackfriday engine outputs one line of footnote while mmark does 3 lines of them with incremental numbers.

**Comment by miekg** [comment]
Ah, they only patched master in that PR. Should not be too hard to get into gomarkdown as well.

**Comment by miekg** [comment]
Kicked off new release as well: 2.0.11
