### ISSUE TITLE
xml: Allow html/xml fallthrough

### ISSUE THREAD

**Issue by miekg** [mmarkdown/mmark#26]
Sometimes you need to fallback to html or xml; currently all blocklevel elements except `<reference>` are removed from the final output. This may be sub optimal.

**Comment by miekg** [comment]
I.e. implement htmlBlock, this is also need for cref conversion (when not a htmlSpan - that works write now)

**Comment by StephanSchmidt** [comment]
+1 

I have a preprocessor which replaces parts of the markdown with HTML (generating arrows with a different styling in code sections) and would need a way to keep HTML.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [mmarkdown/mmark] Allow html/xm..." ]
>+1
>
>I have a preprocessor which replaces parts of the markdown with HTML (generating arrows with a different styling in code sections) and would need a way to keep HTML.

some of this may work already as I did a bit of work here.

**Comment by miekg** [comment]
for html this works, but I want to limit the need for these contructs as they fall flat with e.g. generating manpages.
