### ISSUE TITLE
Spurious [] before cross-references

### ISSUE THREAD

**Issue by fanf2** [mmarkdown/mmark#29]
## What went wrong?

With a long-form xref like [](#RFC2119) the XML output is
```
[]<xref target="RFC2119"></xref>
```
and the HTML is
```
[]<a href="#RFC2119"></a>
```
I expected no [] in the output.

## What version of mmark are you using?

2.0.10

## What command line did you use?

```
echo '[](#RFC2119)' >xref.md
~/go/bin/mmark xref.md
```

## What platform (Linux/Apple/Windows)?

- [*] Linux

**Comment by miekg** [comment]
ah. that looks like an easy fix

**Comment by fanf2** [comment]
Well, it seems that what I *actually* wanted was `[@!RFC2119]` which causes the right XML declarations to be included. I was led astray by converting a draft written using the Pandoc setup. But I think the `[](#thing)` syntax ought to work the same with mmark as with pandoc, e.g. in case of explicit <reference> sections.

**Comment by miekg** [comment]
I'm not in favor (yet) to add more syntax. Even with a `<reference>` to cite it you need a variant `[@....]`.
