### ISSUE TITLE
release needed: gomarkdown broke API for parser.

### ISSUE THREAD

**Issue by bobertlo** [mmarkdown/mmark#60]
# To help us debug your issue please add these details.
The issue #56 was fixed 10 days ago, but this software FTBFS. A stable upstream library or dependency management would be nice, but for now a release would fix this also.

## What went wrong?
Current release FTBFS

## What version of mmark are you using?
Current Release

## What command line did you use?
go build

## What platform (Linux/Apple/Windows)?

- [x] Linux
- [ ] Apple
- [ ] Windows

## What is the *most* minimal markdown snippets that shows the problem?
FTBFS

**Comment by miekg** [comment]
doesn't happen that often, but kicking of a release. 2.0.39 should be there shortly.

**Comment by miekg** [comment]
uh, 2.0.38 I meant. It's there.

**Comment by bobertlo** [comment]
thanks. that was fast :)
