### ISSUE TITLE
Target missing from outputted reference

### ISSUE THREAD

**Issue by j616** [mmarkdown/mmark#61]
## What went wrong?
References including target attributes on reference blocks do not have a target attribute in the outputted xml. It seems this issue was also reported in a comment on issue #53 but never fixed.

## What version of mmark are you using?
2.0.38

## What command line did you use?
```bash
mmark ./test.md > /tmp/x.xml
```

## What platform (Linux/Apple/Windows)?

- [x] Linux

## What is the *most* minimal markdown snippets that shows the problem?
```
%%%

 Title = "Test doc"

 date = 2019-02-19T00:00:00Z

 [seriesInfo] 
 name = "Internet-Draft"
 value = "draft-test-00"
 status = "informational"

 [[author]]
 initials="J."

%%%

{mainmatter}

# Introduction

Test [@!IANA]

{backmatter}

<reference anchor='IANA' target='https://www.iana.org/assignments/media-types/media-types.xhtml'>
    <front>
        <title abbrev='IANA'>IANA Media Types</title>
        <author>
            <organization>IANA</organization>
        </author>
        <date month='February' year='2019'/>
    </front>
</reference>
```

**Comment by jboyd77** [comment]
Do you see the organization in the reference? I am seeing both the missing target and organization.

**Comment by miekg** [comment]
This struct(ure) was fairly incomplete; added the missing bits (well most of it anyway)

**Comment by j616** [comment]
Thanks. Latest version works for me.

**Comment by jboyd77** [comment]
I still see the organization missing. Looking at your commit for the fix, the test will pass if the organization is missing.

    func TestReferenceOrganization(t *testing.T) {
     	in := []byte(`<reference anchor='IANA' target='https://www.iana.org/assignments/media-types/media-types.xhtml'>
         <front>
            <title abbrev='IANA'>IANA Media Types</title>
            <author>
                <organization>IANA</organization>
            </author>
           <date month='February' year='2019'/>
        </front>
       </reference>
    `)
	expect := `<reference anchor="IANA" target="https://www.iana.org/assignments/media-types/media-types.xhtml"><front><title>IANA Media Types</title><author><organization></organization></author><date year="2019" month="February"></date></front></reference>`

**Comment by miekg** [comment]
please open a new issue (and possible a PR to fix things)
