### ISSUE TITLE
mmark math support

### ISSUE THREAD

**Issue by orangelynx** [mmarkdown/mmark#65]
I'm trying to use hugo + mmark + katex. Documentation around the web about math support in mmark is sparse and seems to be partly / mostly outdated.

Using mmark as a markdown processor in hugo, `$$ E = mc^2 $$`  is rendered to `<span class='math'>\( E = mc^2\)</span>` which is valid TeX, but doesn't seem to be compliant with MathJax as is written in most docs, but rather seems to be MathJS syntax (?).

Trying to run

```
$("span[class='math']").replaceWith(
  function(){
    var tex = $(this).text();
    return "<span class=\"inline-equation\">" +
           katex.renderToString(tex) +
           "</span>";
});
```

over it fails because KaTeX cannot deal with the delimiters `\(` and `\)`.

Is there more documentation on math support in mmark that I have missed and is it possible to configure how the math is rendered?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[mmarkdown/mmark] mmark math suppor..." ]
>I'm trying to use hugo + mmark + katex. Documentation around the web about math support in mmark is sparse and seems to be partly / mostly outdated.
>
>Using mmark as a markdown processor in hugo, `$$ E = mc^2 $$``  is rendered to `<span class='math'>\( E = mc^2\)</span>` which is valid TeX, but doesn't seem to be compliant with MathJax as is written in most docs, but rather seems to be MathJS syntax (?).
>
>Trying to run
>
>```
>$("span[class='math']").replaceWith(
>  function(){
>    var tex = $(this).text();
>    return "<span class=\"inline-equation\">" +
>           katex.renderToString(tex) +
>           "</span>";
>});
>```
>
>over it fails because KaTeX cannot deal with the delimiters `\(` and `\)`.
>
>Is there more documentation on math support in mmark that I have missed and is it possible to configure how the math is rendered?

This is done by the upstream library mmark uses: https://github.com/gomarkdown/markdown
