### ISSUE TITLE
Compilation breaks on: # Foo\n\n ### Bar \n\n

### ISSUE THREAD

**Issue by SamuelMarks** [mmarkdown/mmark#67]
Replication steps (mmark 2.0.40, xml2rfc 2.22.0):
```
$ mmark index.md > index.xml
$ xml2rfc index.xml -o index.html
Error: Unable to parse the XML document: index.xml
 <string>: Line 24: Opening and ending tag mismatch: middle line 17 and
section
 <string>: Line 24: Opening and ending tag mismatch: middle line 17 and
section
 <string>: Line 28: Opening and ending tag mismatch: rfc line 3 and section
 <string>: Line 30: Extra content at the end of the document
```

More info:
https://mailarchive.ietf.org/arch/msg/xml2rfc/OPep-8cpM-NZFqQZzX_whWpU9iw

**Comment by miekg** [comment]
Thanks. I replied on list. (there index.md) is not posted here but your go from 
`# header` to `#### header`, you can't do this in the XML, so this is WAI from my standpoint.

**Comment by SamuelMarks** [comment]
The index.md is in that link provided. Should there not be an error before the invalid XML is produced?
