### ISSUE TITLE
[`link`](http://link.link)   fails with Error: Did not expect element t there, at /rfc/middle/t a.xml(3): Error: Invalid document before running preptool

### ISSUE THREAD

**Issue by SamuelMarks** [mmarkdown/mmark#70]
# To help us debug your issue please add these details.

## What went wrong?
Unable to include a link of a code sample. I commonly do this—and see this—on StackOverflow.

## What version of mmark are you using?
2.0.40, and xml2rfc 2.22.0

## What command line did you use?
```
$ mmark a.md > a.xml
$ xml2rfc --v3 a.xml
Parsing file a.xml
a.xml(18): Error: Did not expect element t there, at /rfc/middle/t
a.xml(3): Error: Invalid document before running preptool.
Cannot continue, quitting now
```

## What platform (Linux/Apple/Windows)?

- [ ] Linux
- [x] Apple
- [ ] Windows

## What is the *most* minimal markdown snippets that shows the problem?
```
$ cat a.md
%%%
title = "Model designer"
abbrev = "ODESIGN"
area = "Internet"
workgroup = "Offscale.io"
keyword = ["platform-independent"]
#date = 2019-12-07T00:00:00Z

[seriesInfo]
name = "RFC"
value = "ODESIGN0.0.1"
status = "informational"

[[author]]
surname="Marks"
fullname="Samuel Marks"
organization = "Sydney Scientific"
  [author.address]
  email = "samuel@offscale.io"
%%%

{mainmatter}

You MAY use [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) and/or similar built-ins.

{backmatter}
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[mmarkdown/mmark] [`link`](http://l..." ]
> `You MAY use [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) and/or similar built-ins.`

RFC 7991 XML is very limited and this is not allowed: https://tools.ietf.org/html/rfc7991#section-2.24

/Miek

--
Miek Gieben
