### ISSUE TITLE
Attribute "start" not supported for list style="numbers"

### ISSUE THREAD

**Issue by FiloSottile** [mmarkdown/mmark#75]
## What went wrong?

mmark logs `Attribute "start" not supported for list style="numbers"` and makes the `2.` element of a list start over at `1.`.

## What version of mmark are you using?

v2.0.46

## What command line did you use?

```
mmark -2
```

## What platform (Linux/Apple/Windows)?

- [ ] Linux
- [x] Apple
- [ ] Windows

## What is the *most* minimal markdown snippets that shows the problem?

```
1. Process the internal representation into a field element s as follows:

_some unindented code block here_

2. Return the canonical little-endian encoding of s.
```

**Comment by miekg** [comment]
The codeblock needs to be indented by 4 spaces respective to the list item,
otherwise you end the current list.

**Comment by FiloSottile** [comment]
This is actually fixed by switching to v3, sorry for the noise.
