### ISSUE TITLE
Missing docName

### ISSUE THREAD

**Issue by FiloSottile** [mmarkdown/mmark#76]
## What went wrong?

`xml2rfc --v3` complained with `Warning: Expected a 'docName' attribute in the <rfc/> element, but found none.`, and https://datatracker.ietf.org/submit/ rejected the XML.

Manually adding the `docName` attribute fixed the issue.

## What version of mmark are you using?

2.0.46

## What command line did you use?

`mmark`

## What platform (Linux/Apple/Windows)?

- [ ] Linux
- [x] Apple
- [ ] Windows

## What is the *most* minimal markdown snippets that shows the problem?

```
%%%

    Title = "The ristretto255 Group"
    abbrev = "ristretto255"
    ipr = "trust200902"
    category = "info"
    area = "Internet"
    workgroup = "Crypto Forum Research Group"

    [seriesInfo]
    status = "informational"
    name = "Internet-Draft"
    value = "draft-hdevalence-cfrg-ristretto-01"
    stream = "IETF"

[...]
```

**Comment by miekg** [comment]
I've raised this on the xml2rfc-dev list; RFC 7991 says it's removed, but xml2rfc still implements it and IETF now rejects it.

This is in part because the XMLv3 effort is not going too well... For docName you re-used seriesInfo.value?

**Comment by miekg** [comment]
See https://mailarchive.ietf.org/arch/browse/xml2rfc-dev/?qdr=d

This is easily fixed, but I'm not sure what the final way of doing this will be and if this would invalidate any XML now generated :/

**Comment by miekg** [comment]
Per https://mailarchive.ietf.org/arch/browse/xml2rfc-dev/?qdr=d

>  I'd like to know the rejection message from the datatracker.  There are
any number of possible rejection reasons that have nothing to do with
docName, even if the description in #76 seems to indicate that it's related.

> I may be able to fish the rejection reason out if I know the draft name and
submission date.  Could you provide that?

>I'll check the code to see if the warning should be an error, but would really
like to see the rejection message to understand what's up.

>> I know need to make code changes for something that is actually not described 
>> anywhere, but seems mandatory.

>You can expect that docName will continue to be needed.

**Comment by FiloSottile** [comment]
The rejection reason was

> No docName attribute found in the xml root element

I am pretty sure it's about `docName` 😄 and simply setting it to `seriesInfo.value` generated what is now `draft-hdevalence-cfrg-ristretto-01`.

**Comment by miekg** [comment]
See https://github.com/mmarkdown/mmark/pull/77, can you test? I don't have a I-D laying around (although some test I-D might make sense here)

**Comment by miekg** [comment]
Should be fixed iwth #77

**Comment by dunglas** [comment]
Hi, this doesn't look to be fixed.

`xml2rfc` also wants the `docName` attribute on the `rfc` element.
If it helps, you can try with this ID: https://github.com/dunglas/mercure/blob/master/spec/mercure.md

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [mmarkdown/mmark] Missing docNa..." ]
>Hi, this doesn't look to be fixed.
>
>`xml2rfc` also wants the `docName` attribute on the `rfc` element.
>If it helps, you can try with this ID: https://github.com/dunglas/mercure/blob/master/spec/mercure.md

~~~
% grep docName render/xml2/title.go                            ~/go/mmark master
		attrs = append(attrs, `docName="`+d.SeriesInfo.Value+"\"")
~~~

/Miek

--
Miek Gieben
