### ISSUE TITLE
Add a shortcut for non-breaking spaces

### ISSUE THREAD

**Issue by cyChop** [mmarkdown/mmark#80]
# Feature request

## Description

The use of non-breaking spaces is useful for better typography and indispensable in some languages, furthermore when writing long texts (documentation, books, or just blog posts).

However, inserting `&nbsp;` in all files is not ideal as it is tiresome _and_ can bring some brittleness (it only works as long as the target rendering is HTML).

Could we think of a universal shortcut that would be rendered appropriately?

## Some use cases

* This can be useful to make sure that references stay together: `See Fig.&nbsp;3`.
* This should be used when writing something with a unit: `Processing time: 25&nbsp;ms`.
* In some ~~languages~~ countries, typographic rules make heavy use of the non-breaking space. This is for example the case in France, where `:`, `;`, `?` and `!` should be preceded with a non-breaking space: `Et il déclara&nbsp;: «&nbsp;Que c'est pénible d'écrire correctement&nbsp;! Faut-il systématiquement saisir six caractères pour une espace&nbsp;?&nbsp;»`

## Existing solutions in other software

* AsciiDoctor predefines a `{nbsp}` variable. It is as verbose as writing `&nbsp;` but rules out the brittleness as it can be treated differently depending on the renderer.
* Some other Markdown parsers use an escaped space (`\ `) or a tilde (`~`) as a non-breaking space. For instance: `42\ ms, 1337~ms`.

**Comment by miekg** [comment]
Pandoc seems to use backslash-space for this. Seems like a small, and
useful addition.

**Comment by cyChop** [comment]
Indeed, I think I saw the `\ ` about pandoc. :)

**Comment by cyChop** [comment]
Just an afterthought: for exigent people, French does not use non-breaking space for big punctuation. It uses [_narrow_ non breaking space](https://en.wikipedia.org/wiki/Non-breaking_space#Width_variation) (`U+202F`). As a French, exigent people, I'd love to have a shortcut for that one too, even though I know we can't include everything inside the software. :)
