### ISSUE TITLE
submissionType is hardcoded to "IETF"

### ISSUE THREAD

**Issue by hawkowl** [mmarkdown/mmark#83]
# What went wrong?

The submissionType in the XML output is hardcoded to `IETF` (https://github.com/mmarkdown/mmark/blob/master/render/xml/title.go#L42) and setting `seriesInfo.stream` to "independent" as per https://mmark.miek.nl/post/syntax/#title-block causes xml2rfc to barf:

```
Error: The stream setting of <seriesInfo> is inconsistent with the submissionType of <rfc>.  Found independent, IETF
```

## What version of mmark are you using?

2.0.48

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[mmarkdown/mmark] submissionType is..." ]
># What went wrong?
>
>The submissionType in the XML output is hardcoded to `IETF` (https://github.com/mmarkdown/mmark/blob/master/render/xml/title.go#L42) and setting `seriesInfo.stream` to "independent" as per https://mmark.miek.nl/post/syntax/#title-block causes xml2rfc to barf:
>
>```
>Error: The stream setting of <seriesInfo> is inconsistent with the submissionType of <rfc>.  Found independent, IETF
>```
>
>## What version of mmark are you using?
>
>2.0.48

I think this entire flow is now broken in xml2rfc, at least I couldn't get it 
to work. If you have some handedited xml that compiles with a current xml2rfc, 
I'm happy to make changes to mmark.

**Comment by hawkowl** [comment]
Amending the `<rfc>` tag to contain `submissionType="independent"` and removing the `consensus="yes"` attribute renders fine on the latest version of xml2rfc, here.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [mmarkdown/mmark] submissionTyp..." ]
>Amending the `<rfc>` tag to contain `submissionType="independent"` and removing the `consensus="yes"` attribute renders fine on the latest version of xml2rfc, here.

this should work (hopefully): https://github.com/mmarkdown/mmark/commit/a988fb2d22d173d904c84078b21ad03d8f725667

Now merged into master, so you can just use that.

**Comment by miekg** [comment]
How do you get rid of the default IPR crap that still pops up in an independent submission?

**Comment by hawkowl** [comment]
@miekg Set `ipr = "none"` in the header, and it'll remove it.

(I haven't had a chance to check if the changes to `mmark` work for me, yet, btw, I'll get to that Monday)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [mmarkdown/mmark] submissionTyp..." ]
>@miekg Set `ipr = "none"` in the header, and it'll remove it.
>
>(I haven't had a chance to check if the changes to `mmark` work for me, yet, btw, I'll get to that Monday)

Ok, thanks. That actually works now :)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [mmarkdown/mmark] submissionTyp..." ]
>@miekg Set `ipr = "none"` in the header, and it'll remove it.
>
>(I haven't had a chance to check if the changes to `mmark` work for me, yet, btw, I'll get to that Monday)

Cool, I've started a FAQ.md with this stuff, 'cause I also (always) forget how 
to do things like this. Will be soon putting this on the website as well.
