### ISSUE TITLE
Handle Parenthesis in links properly

### ISSUE THREAD

**Issue by cup** [mmarkdown/mmark#98]
Using this file:

~~~
$ cat input.md
https://en.wikipedia.org/wiki/The_Master_(2012_film)
~~~

I get this result:

~~~html
$ mmark -html input.md
<!DOCTYPE html>
<html>
<!-- ... -->
<body>
<p><a href="https://en.wikipedia.org/wiki/The_Master_(2012_film"
>https://en.wikipedia.org/wiki/The_Master_(2012_film</a>)</p>
</body>
</html>
~~~

Note that the final parenthesis is not included as part of the link. Other
processors work as expected. For example GitHub parser:

https://en.wikipedia.org/wiki/The_Master_(2012_film)

**Comment by cup** [comment]
https://github.com/russross/blackfriday/issues/116

**Comment by cup** [comment]
https://github.com/russross/blackfriday/pull/358

**Comment by cup** [comment]
Here is a workaround:

~~~go
package main
import (
   "bytes"
   "github.com/yuin/goldmark"
   "github.com/yuin/goldmark/extension"
)
func main() {
   s1 := "https://en.wikipedia.org/wiki/The_Master_(2012_film)"
   o1 := goldmark.New(goldmark.WithExtensions(extension.Linkify))
   var b2 bytes.Buffer
   o1.Convert([]byte(s1), &b2)
   s2 := b2.String()
   print(s2)
}
~~~

https://github.com/yuin/goldmark

**Comment by cup** [comment]
https://github.com/gohugoio/hugo/issues/5963

https://github.com/mmarkdown/mmark/issues/98
https://github.com/russross/blackfriday/pull/358

**Comment by miekg** [comment]
Enclose the link with `<` and `>`
